harvard/urls.py
from django.contrib import admin
from django.urls import include, path, reverse
from django.conf import settings
from django.conf.urls.static import static

from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace='todo')),
    path('accounts/', include('django.contrib.auth.urls')), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps.views import (
     index as site_index_view)
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from harvard.sitemaps import sitemaps as sitemaps_dict

from . import views
from harvard.sitemaps import StaticSitemap, TaskListViewSitemap, TaskViewSitemap, AttachmentViewSitemap
from .views import (
    TaskListView, TaskView, AttachmentView, 
    TaskListDetail, TaskDetail, AttachmentDetail, 
    TaskListAdd, TaskAdd, AttachmentAdd, 
    TaskListEdit, TaskEdit, AttachmentEdit, 
    TaskListDelete, TaskDelete, AttachmentDelete,
    settings, contact, about, 
)


app_name = "todo"


sitemaps = {
    'static': StaticSitemap,
    'tasklists': TaskListViewSitemap,
    'tasks': TaskViewSitemap,
    'attachment': AttachmentViewSitemap,
}


urlpatterns = [
    path('tasklists/', TaskListView.as_view(), name= 'tasklists'),
    path('tasks/', TaskView.as_view(), name= 'tasks'),
    path('attachments/', AttachmentView.as_view(), name= 'attachments'),
    
    path('addlist/', TaskListAdd.as_view(), name= 'addlist'),
    path('addtask/', TaskAdd.as_view(), name= 'addtask'),
    path('addattachment/', AttachmentAdd.as_view(), name= 'addattachment'),
    
    path('tasklist/<int:pk>', TaskListDetail.as_view(), name= 'tasklist'),
    path('task/<int:pk>', TaskDetail.as_view(), name= 'task'),
    path('attachment/<int:pk>', AttachmentDetail.as_view(), name= 'attachment'),
    
    path('editlist/<int:pk>', TaskListEdit.as_view(), name= 'editlist'),
    path('edittask/<int:pk>', TaskEdit.as_view(), name= 'edittask'),
    path('editattachment/<int:pk>', AttachmentEdit.as_view(), name= 'editattachment'),
    
    path('deletelist/<int:pk>', TaskListDelete.as_view(), name= 'deletelist'),
    path('deletetask/<int:pk>', TaskDelete.as_view(), name= 'deletetask'),
    path('deleteattachment/<int:pk>', AttachmentDelete.as_view(), name= 'deleteattachment'),
    
    path('settings/', views.settings, name= 'settings'),
    path('about/', views.about, name= 'about'),
    path('contact/', views.contact, name= 'contact'),
    path('terms-conditions/', views.contact, name= 'terms'),
    
    path('index/', site_index_view, {'sitemaps': sitemaps_dict, 'template_name': 'index.html'}, name='index'),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps, 'template_name':'sitemap.xml', 'template_name': 'sitemap.xml'}, name='sitemap')    
]

todo/models.py
import datetime
import os
import textwrap

from django.core.files.base import ContentFile
from django.conf import settings
from django.contrib.auth.models import User
from django.db import DEFAULT_DB_ALIAS, models
from django.db.transaction import Atomic, get_connection
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from datetime import datetime, timedelta


def get_attachment_upload_dir(instance, filename):
    return "/".join(["tasks", "attachment", str(instance.task.id), filename])
 		    
class LockedAtomicTransaction(Atomic):
	
	def __init__(self, *models, using=None, savepoint=None):
		if using is None:
			using= Default_DB_Alias
		super().__init__(using, savepoint)
		self.models= models
		
	def __enter__(self):
		super(LockedAtomicTransaction, self).__enter__()
		
		if settings.DATABASE[self.using]["Engine"] != "django.db.backends.sqlite3":
			cursor=None
			try:
				cursor= get.connection(self.using).cursor()
				for model in self.models:
					cursor.execute("LOCK TABLE {table_name}".format(table_name=model._meta.db_table))
			finally:
				if cursor and not cursor.closed:
					cursor.close()

# Create your models for the admin area here.
# New Database class Todo-"List" and add new todo-task to list
class List(models.Model):  
    name= models.CharField(max_length=900) #add new todo to list, varchar
    created_by= models.ForeignKey('auth.User', on_delete=models.CASCADE,)
    assigned_to= models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name= "todo_list_assigned_to", on_delete=models.CASCADE,)
    slug= models.SlugField(max_length=5)
    note= models.TextField()
    completed= models.BooleanField(default= False) #checkbox
    # Maps to create_date table column.
    date= models.DateTimeField(default=datetime.now, blank=True, null= True)
    updated_at= models.DateTimeField(auto_now=True, null=True)
    
    def __str__(self):
    	return self.name + ' | | List-ID: ' + str(self.id) 
    	
    def get_absolute_url(self):
    	self.model.__name__
    	return reverse('tasklist', args={"list_id": str(self.id)})
    	
    class Meta:
    	ordering=["name", "assigned_to", "date"]
    	verbose_name_plural="Task Lists"
    	unique_together= ("created_by", "slug")
    	unique_together= ("assigned_to", "slug")
    	
 		
class Task(models.Model):
    STATUS= [
    ('TODO', 'TODO'),
    ('IN PROGRESS', 'IN PROGRESS'),
    ('PAUSE', 'PAUSE'),
    ('DONE', 'DONE'),
    ]
    
    PRIORITY= [
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    (6, '6'),
    (7, '7'),
    (8, '8'),
    (9, '9'),
    (10, '10'),
    ]
 		
    task_list= models.ForeignKey(List, on_delete= models.CASCADE, null=True)
    created_by= models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="todo_created_by", on_delete=models.CASCADE,)
    assigned_to= models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="todo_task_assigned_to", on_delete=models.CASCADE,)
    title= models.CharField(max_length=900) #add new todo to list, varchar
    slug= models.SlugField(max_length=5)
    note= models.TextField(blank= True, null= True)
    priority= models.IntegerField(choices= PRIORITY)
    status= models.CharField(max_length= 15, choices=STATUS)
    # Maps to create_date table column.
    created_date= models.DateTimeField(default=datetime.now, blank=True, null= True)
    updated_at= models.DateTimeField(auto_now=True, null=True)
    due_date= models.DateField(default=datetime.now()+timedelta(days=15), blank=True, null=True)
    completed= models.BooleanField(default= False) #checkbox
    
    def get_absolute_url(self):
        self.model.__name__
        return reverse('task', args={"task_id": str(self.id)})
    
    def overdue_status(self):
        "Returns wether the Task's due date has passed or not."
        if self.due_date and datetime.today() > self.due_date:
            return True
            
    def __str__(self):
        return self.title  + ' | | from Task List: ' + self.task_list.name
 		
    def save(self, **kwargs):
        if self.completed:
            self.completed_date= datetime.now()
        super(Task,self).save()
        
    def merge_into(self, merge_target):
        if merge_target.pk == self.pk:
            raise ValueError("can't merge a task with self")
            
        with LockedAtomicTransaction(Attachement):
            Attachement.objects.filters(task.self).update(task=merge_target)
            self.delete()
 	
    class Meta:
        ordering= ["task_list", "title", "due_date", "priority", "status"]
       
        
class Attachment(models.Model):
    task= models.ForeignKey(Task, on_delete= models.CASCADE, null= True)
    file_name= models.CharField(max_length=900, blank=True, null=True) 
    added_by= models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="todo_added_by",  on_delete=models.CASCADE,)
    timestamp= models.DateTimeField(default=datetime.now, blank=True, null=True)
    note= models.TextField(blank= True, null= True)
    file= models.FileField(upload_to= 'media/', max_length=855)
 		
    def get_absolute_url(self):
        self.model.__name__
        return reverse('attachment', args={"attachment_id": str(self.id)})
 		
    def filename(self):
        return os.path.basename(str(self.file_name))
 			
    def extension(self):
        name, extension= os.path.splitext(str(self.file.name))
        return extension
 			
    def __str__(self):
        return f"{self.task.title} - from: {self.task.task_list.name} - {self.file_name}"
 			
    def get_attachment_upload_dir(instance, file_name):
        return "/".join(["tasks", "attachment", str(instance.task.id), file_name])
    
    class Meta:
        ordering= ["task", "timestamp"]

todo/views.py
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse, reverse_lazy, Resolver404, resolve, NoReverseMatch
from django.views import generic
from django.template.loader import render_to_string
from django.contrib import messages
from django.db import migrations, models
from django.views.generic import (
    ListView, 
    DetailView, 
    UpdateView,
    DeleteView, 
    CreateView,
)
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from harvard.sitemaps import StaticSitemap, TaskListViewSitemap, TaskViewSitemap


from .models import List, Task, Attachment


time=["5:00 a.m.", "5:15 a.m.", "5:30 a.m.", "5:45 a.m.", "6:00 a.m.", "6:15 a.m.", "6:30 a.m.", "6:45 a.m.", "7:00 a.m.", "7:15 a.m.", "7:30 a.m.", "7:45 a.m.", "8:00 a.m.", "8:15 a.m.", "8:30 a.m.", "8:45 a.m.", "9:00 a.m.", "9:15 a.m.", "9:30 a.m.", "9:45 a.m.", "10:00 a.m.", "10:15 a.m.", "10:30 a.m.", "10:45 a.m.", "11:00 a.m.", "11:15 a.m.", "11:30 a.m.", "11:45 a.m.","12:00 a.m.", "12:15", "12:30", "12:45",  "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30", "22:45", "23:00", "23:15", "23:30", "23:45", "00:00", "00:15", "00:30", "00:45", "1:00 a.m.", "1:15 a.m.", "1:30 a.m.", "1:45 a.m.", "2:00 a.m.", "2:15 a.m.", "2:30 a.m.", "2:45 a.m.", "3:00 a.m.", "3:15 a.m.", "3:30 a.m.", "3:45 a.m.", "4:00 a.m.", "4:15 a.m.", "4:30 a.m.", "4:45 a.m."]

def upload(request):
    if request.method == 'POST' and request.FILES['addattachment']:
        upload= request.FILES['addattachment']
        fss= FileSystemStorage()
        file= fss.save(upload.name, upload)
        file_url= fss.url(file)
        return render(request, 'todo/attachments.html', {'file.url': file_url})
    return render(request, 'todo/attachments.html')   
    
def index(request):
    return HttpsResponse('todo:index')    
    
#ADD ONE	
class TaskListAdd(CreateView):
	model= List
	template_name= 'todo/addlist.html'
	success_url= reverse_lazy('todo:tasklist')
	fields= '__all__'
	
	def get_absolute_url(self):
		return reverse('todo/tasklist')
	
class TaskAdd(CreateView):
	model= Task
	template_name= 'todo/addtask.html'
	success_url= reverse_lazy('todo:task')
	fields= '__all__'
	
	def get_absolute_url(self):
		return reverse('todo/task')
	
class AttachmentAdd(CreateView):
	model= Attachment
	template_name= 'todo/addattachment.html'
	success_url= reverse_lazy('todo:attachment')
	fields= '__all__'
	
	def get_success_url(self): 
		return reverse('todo:attachment')
		
	

#View all
class TaskListView(ListView):
	model= List
	template_name= 'todo/tasklists.html'
	context_object_name= 'all_lists'
	
	def __str__(self):
		return '__all__'
        
        
	
class TaskView(ListView):
	model= Task
	template_name= 'todo/tasks.html'
	context_object_name= 'all_tasks'
	
	def __str__(self):
		return '__all__'
        
	def get_context_data(self, **kwargs):
		context= super(TaskView, self).get_context_data(**kwargs)
		context['all_objects']= Task.objects.all()
	    
		return context    
	
class AttachmentView(ListView):
	model= Attachment
	template_name= 'todo/attachments.html'
	context_object_name= 'all_attachments'
	
	def __str__(self):
		return '__all__'

#View each		
class TaskListDetail(DetailView):
	model= List
	queryset= List.objects.all()
	template_name= 'todo/tasklist.html'
	context_object_name= 'indiv_list'
	
	def __str__(self):
		return ['title', 'task_list.name', 'priority', 'status', 'str(id) ',  'completed']
		
	def get_context_data(self, **kwargs):
	    context= super(TaskListDetail, self).get_context_data(**kwargs)
	    context['all_objects']= List.objects.all()
	    
	    return context
	
class TaskDetail(DetailView):
	model= Task
	queryset= Task.objects.all()
	template_name= 'todo/task.html'
	context_object_name= 'indiv_task'
	
	def __str__(self):
		return '__all__'
		
	def get_context_data(self, **kwargs):
	    context= super(TaskDetail, self).get_context_data(**kwargs)
	    context['all_objects']= Task.objects.all()
	    
	    return context
	
class AttachmentDetail(DetailView):
	model= Attachment
	queryset= Attachment.objects.all()
	template_name= 'todo/attachment.html' 
	context_object_name= 'indiv_attachment'
	fields= '__all__'
	
	def get_success_url(self): 
		return '__all__'
		
	def get_context_data(self, **kwargs):
	    context= super(AttachmentDetail, self).get_context_data(**kwargs)
	    context['all_objects']= Attachment.objects.all()
	    
	    return context
	
#Edit each		
class TaskListEdit(UpdateView):
	model= List
	template_name= 'todo/editlist.html'
	context_object_name= 'edit_list'
	fields= '__all__'
	
	def get_success_url(self): 
		return reverse('todo:tasklist', kwargs={'pk': self.object.pk})
        
	def get_context_data(self, **kwargs):
		context= super(TaskListEdit, self).get_context_data(**kwargs)
		context['all_objects']= List.objects.all()  

		return context        
	
class TaskEdit(UpdateView):
	model= Task
	template_name= 'todo/edittask.html'
	context_object_name= 'edit_task'
	fields= '__all__'
	
	def get_success_url(self): 
		return reverse('todo:task', kwargs={'pk': self.object.pk})
        
	def get_context_data(self, **kwargs):
		context= super(TaskEdit, self).get_context_data(**kwargs)
		context['all_objects']= Task.objects.all() 

		return context        
	
class AttachmentEdit(UpdateView):
	model= Attachment
	template_name= 'todo/editattachment.html'
	context_object_name= 'edit_attachment'
	fields= '__all__'
	
	def get_success_url(self):
		return reverse('todo:attachment', kwargs={'pk': self.object.pk})
		
	def get_context_data(self, **kwargs):
		context= super(AttachmentEdit, self).get_context_data(**kwargs)
		context['all_objects']= Attachment.objects.all()
        
		return context        
		
#Delete each		
class TaskListDelete(DeleteView):
	model= List
	template_name= 'todo/deletelist.html'
	context_object_name= 'edit_list'
	success_url= reverse_lazy('todo:tasklists')
	fields= '__all__'
	
	def get_absolute_url(self):
		return reverse_lazy('todo/tasklists')
        
	def get_context_data(self, **kwargs):
		context= super(TaskListDelete, self).get_context_data(**kwargs)
		context['all_objects']= List.objects.all()    
        
		return context
	
class TaskDelete(DeleteView):
	model= Task
	template_name= 'todo/deletetask.html'
	context_object_name= 'edit_task'
	success_url= reverse_lazy('todo:tasks')
	fields= '__all__'
	
	def get_absolute_url(self):
		return reverse_lazy('todo/tasks')
        
	def get_context_data(self, **kwargs):
		context= super(TaskDelete, self).get_context_data(**kwargs)
		context['all_objects']= Task.objects.all()    

		return context
        
class AttachmentDelete(DeleteView):
	model= Attachment
	template_name= 'todo/deleteattachment.html'
	context_object_name= 'delete_attachment'
	success_url= reverse_lazy('todo:attachments')
	fields= '__all__'
	
	def get_absolute_url(self):
		return reverse_lazy('todo/attachments')

	def get_context_data(self, **kwargs):
		context= super(AttachmentDelete, self).get_context_data(**kwargs)
		context['all_objects']= Attachment.objects.all()

		return context

# Create your views here
def tasks(request):
    messages.success(request, ('Task has been added to your List successfully!'))
    return render(request, 'todo/tasks.html', {
            "form": form, "todo": todo, "time": time,
    }) #reloading the page
    		  
def settings(request):	
    return render(request, 'todo/settings.html', {})	

def about(request):	
    return render(request, 'todo/about.html', {})	

def contact(request):	
    my_name= "Maricla Martelli Kandzorra"	
    return render(request, 'todo/contact.html', {
        'name': my_name
    })

todo/templates/todo/attachment.html
{% extends 'todo/base.html' %}

<title>{% block title %}Attachment{% endblock %}</title>

{% block content %}

<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2">YOUR ATTACHMENT</thread>
</div>
<br><br>    
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="#"> {{ object.file }} </a><br><p class="fw-light text-center fs-10"> From Task: {{ object.task }} </p><p class="fw-light text-center fs-10">Added by: {{ object.added_by }}</p><p class="fw-light text-center fs-5"><span class="glyphicon glyphicon-calendar">Uploaded on: {{ object.timestamp }}</span>
</p><p class="fw-light text-center fs-5">Task ID: {{ object.id }}</p></thread></div>
<br>
<div class="container-fluid alert alert-secondary fw-bold fs-5" role="alert" rows="3">{{ object.note  }}</div>

<tr> <td><ul class="nav justify-content-end">
<a href="{% url 'todo:editattachment' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary" style="margin-right: 10px">Edit</button></a>
<a href="{% url 'todo:deleteattachment' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary" style="margin-right: 10px"> Delete</button></a>
</ul></td></tr>    
</table>


<table class="table"><br><br>
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="{% url 'todo:attachments' %}">YOUR ATTACHMENTS</a></thread>
</div>
<br>
{% for attachment in object.list_set.all %} 
<tr>  
<td class="text-center"><p class="text-md-center fw-bold fs-2 bg-light border"><a href="{% url 'todo:attachment' pk=attachment.id %}">{{ object.file_name }} </a></p><p class="fw-light text-justified alert-secondary"><br> From Task: {{ object.task }} | | Created on: {{ object.timestamp }}<br></p>
<p class="fw-light text-justified"> Attachment ID: {{ object.id }}</p>
</td>
<tr><td>
<ul class="nav justify-content-end">  
<a href="{% url 'todo:editattachment' pk=object.id %}"><button type="submit" name="button" class="btn btn-info text-primary" style="background-color: #FFD700">Edit</button></a>

<a href="{% url 'todo:deleteattachment' pk=object.id %}"> <button type="submit" name="button" class="btn btn-info text-primary" style="background-color: #FFD700">Delete</button></a>
</ul></tr></td>
{% endfor %}
</tr>
</table>
{% endblock %}

todo/templates/todo/task.html
{% extends 'todo/base.html' %}

<title>{% block title %}Task{% endblock %}</title>

{% block content %}
<table class="table">
{% if object.completed %} 
<div class="container-fluid bg-warning text-center">
<thread class="thread text-md-center fw-bold fs-2" style="color: #40ff00">MISSION ACCOMPLISHED</thread>
</div>
<br><br>   

<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"> <a href="#"><s>{{ object.title }}</s></a><p> <span class="glyphicon glyphicon-calendar"><s>  Due Date: {{ object.due_date }}</s></span></p><s><p class="fw-light text-center fs-5"> Task ID: {{ object.id }} || Priority: {{ object.priority }} | | Status: {{ object.status }} || Assigned to: {{ object.assigned_to }}</p></s><p class="fw-light text-center fs-5"> <span class="glyphicon glyphicon-calendar"><s>Created on: {{ object.created_date }}</s></span></p></thread></div>
<tr>
<td><ul class="nav justify-content-end"><a href="{% url 'todo:edittask' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary">Restore</button></a>
</ul></td></tr> 
{% else %} 
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2">YOUR TASK</thread>
</div>
<br><br>    
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="#">{{ object.title }}</a><p> <span class="glyphicon glyphicon-calendar">Due Date: {{ object.due_date }}</span></p><p class="fw-light text-center fs-5"> Task ID: {{ object.id }} || Priority: {{ object.priority }} | | Status: {{ object.status }} <p class="fw-light text-center fs-5">Assigned to: {{ object.assigned_to }}</p><p class="fw-light text-center fs-5"> <span class="glyphicon glyphicon-calendar">Created on: {{ object.created_date }}</span></p></thread></div>
<br>
<div class="container-fluid alert alert-secondary fw-bold fs-5" role="alert" rows="3">{{ object.note  }}</div>

<tr> <td>
<ul class="nav justify-content-end">
<a href="{% url 'todo:edittask' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary" style="margin-right: 10px">Edit</button></a>
<a href="{% url 'todo:deletetask' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary" style="margin-right: 10px"> Delete</button></a>
</ul></td></tr>    
    
{% endif %}
</table>

<table class="table"><br><br>
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="{% url 'todo:tasks' %}">YOUR TASKS</a></thread>
</div>
<br>
<div class="container-fluid text-center">

{% for object in object.list_set.all %} 
<tr>        
<td class="text-center"><p class="text-md-center fw-bold fs-2 bg-light border"><a href="{% url 'todo:task' pk=object.id %}">{{ object.title }}</a> </p><br><p class="fw-light text-justified"> | | List ID: {{ object.id }} | | Created on: {{ object.created_date }}</p></td>   
<td>  
<a href="{% url 'todo:edittask' pk=object.id %}"><button type="submit" name="button" class="btn btn-info text-white" style="background-color: #FFD700">Edit</button></a>
<br><br>
<a href="{% url 'todo:deletetask' pk=object.id %}"><button type="submit" name="button" class="btn btn-info text-white" style="background-color: #FFD700"> Delete</button></a>
</td>
</tr>    

{% endfor %}
</div>   
</table>
{% endblock %}

todo/templates/todo/tasklist.html
{% extends 'todo/base.html' %}

<title>{% block title %}Task List{% endblock %}</title>

{% block content %}
<table class="table">
{% if object.completed %} 
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2" style="color: #40ff00">MISSION ACCOMPLISHED</thread>
</div>
<br><br>   

<div class="container-fluid bg-warning text-center"><s>
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="#">{{ object.name }}</a> <br><p class="fw-light text-center fs-10">List ID: {{ object.id }} || Assigned to: {{ object.assigned_to }}</s></p><p class="fw-light text-center fs-5"><span class="glyphicon glyphicon-calendar"><s> Created on: {{ object.date }}</s></span></p></thread></div>
<br>
<div class="container-fluid alert alert-secondary fw-bold fs-5" role="alert" rows="3"><s>{{ object.note  }}</s></div>
<tr><td>
<ul class="nav justify-content-end"><a href="{% url 'todo:editlist' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary">Restore</button></a>
</ul></td></tr> 
{% else %} 
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2">YOUR TASK LIST</thread>
</div>
<br><br>    
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="#">{{ object.name }}</a> <br><p class="fw-light text-center fs-10">List ID: {{ object.id }} || Assigned to: {{ object.assigned_to }}</p><p class="fw-light text-center fs-5"><span class="glyphicon glyphicon-calendar"> Created on: {{ object.date }}</span></p></thread></div>
<br>
<div class="container-fluid alert alert-secondary fw-bold fs-5" role="alert" rows="3">{{ object.note  }}</div>

<tr> <td>
<ul class="nav justify-content-end">
<a href="{% url 'todo:editlist' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary" style="margin-right: 10px">Edit</button></a>
<a href="{% url 'todo:deletelist' pk=object.id %}"><button type="submit" name="button" class="btn btn-info bg-warning text-primary" style="margin-right: 10px"> Delete</button></a>
</ul></td></tr>      
{% endif %}
</table>

<table class="table"><br><br>
<div class="container-fluid bg-warning text-center">
<thread class="thread text-center text-md-center fw-bold fs-2"><a href="{% url 'todo:tasklists' %}">YOUR LISTS</thread>
</div>
<br>
<div class="container-fluid text-center">

{% for list in object.list_set.all %} 


<tr>        
<td class="text-center"><p class="text-md-center fw-bold fs-2 bg-light border"><a href="{% url 'todo:tasklist' pk=object.id %}">{{ object.name }}</a> </p><br><p class="fw-light text-justified"> | | List ID: {{ object.id }} | | Created on: {{ object.date }}</p></td>   
<td>  
<button type="submit" name="button" class="btn btn-info text-white" style="background-color: #FFD700"><a href="{% url 'todo:editlist' pk=object.id %}">Edit</a></button>
<br><br>
<button type="submit" name="button" class="btn btn-info text-white" style="background-color: #FFD700"><a href="{% url 'todo:deletelist' pk=object.id %}"> Delete</a></button>
</td>
</tr>    

{% endfor %}
</div>    
</table>
{% endblock %}